baseURL = 'https://droledevelo.fr/'
languageCode = 'fr-fr'
title = 'Drôle de vélo'
theme = "DroleDeVelo"

[params]
  githubURL = "https://github.com/europrimus/droledevelo.fr"

[params.author]
    name = "Didier COURTY"
    email = "bonjour@droledevelo.fr"

[params.logo]
  favicon = "/img/icon.png"
  logo = "/img/droledevelo.png"